# Generated by Django 3.2.8 on 2021-12-27 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default='', max_length=40)),
                ('description', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(default='', max_length=40)),
                ('subdescription', models.TextField(max_length=40)),
                ('categoryname', models.OneToOneField(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('current_address', models.CharField(blank=True, default='-NA-', max_length=250)),
                ('email', models.EmailField(default='', max_length=90)),
                ('mobile', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format', regex='^[6-9]\\d{9}$')])),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodmodelname', models.CharField(max_length=60)),
                ('modeldescription', models.CharField(max_length=60)),
                ('subcatname', models.ManyToManyField(default='', to='inventory.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=40)),
                ('productdescri', models.CharField(max_length=40)),
                ('productunit', models.IntegerField()),
                ('pricebuy', models.FloatField()),
                ('pricesell', models.FloatField()),
                ('productavil', models.IntegerField()),
                ('prouctdate', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('productadded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productmodel', models.ManyToManyField(default='', to='inventory.SubCatModel')),
                ('subcategory', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory')),
            ],
        ),
    ]
