# Generated by Django 3.2.8 on 2021-12-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_subcatmodel_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productavil',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productadded',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.RemoveField(
            model_name='product',
            name='productmodel',
        ),
        migrations.AddField(
            model_name='product',
            name='productmodel',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subcatmodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.subcategory'),
        ),
        migrations.RemoveField(
            model_name='subcatmodel',
            name='subcatname',
        ),
        migrations.AddField(
            model_name='subcatmodel',
            name='subcatname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory'),
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=60)),
                ('categoryname', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('subcatname', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productbrand',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbrand'),
        ),
        migrations.AddField(
            model_name='subcatmodel',
            name='brandname',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='inventory.productbrand'),
        ),
    ]
