# Generated by Django 3.2.8 on 2021-12-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211227_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productadded',
            new_name='productaddedby',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prouctdate',
            new_name='prouctdateadded',
        ),
    ]
