# Generated by Django 3.2.8 on 2021-12-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20211227_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='categoryname',
            new_name='categorynamebran',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='categoryname',
            new_name='categorynamesub',
        ),
        migrations.RenameField(
            model_name='subcatmodel',
            old_name='categoryname',
            new_name='categorynamemod',
        ),
    ]
