# Generated by Django 3.2.8 on 2021-12-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20211228_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='categorynamesub',
            new_name='categname',
        ),
    ]
