# Generated by Django 3.2.8 on 2022-01-02 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_auto_20211229_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('orderedat', models.DateTimeField(auto_now_add=True)),
                ('arrivedat', models.DateTimeField(auto_now_add=True)),
                ('arrived', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderunitprice', models.FloatField()),
                ('ordersize', models.FloatField(max_length=40)),
                ('orderqty', models.IntegerField()),
                ('orderdiscount', models.FloatField()),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('ordertotal', models.FloatField()),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('orderdtl', models.TextField(max_length=40)),
                ('status', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordergenerate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('productorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
