# Generated by Django 3.2.8 on 2022-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20220102_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupply',
            name='arrivedat',
            field=models.DateTimeField(blank=True),
        ),
    ]
